permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    branches: [main]
    types: [opened, reopened]
  pull_request_review:
    types: [submitted]

jobs:
  assign-and-merge:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ PR 열릴 때: 리뷰어 지정 및 PR 본문에 기록
      - name: Assign random contributors as reviewers & save to PR body
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_ACCESS_TOKEN }}
          script: |
            // 모든 기여자 목록 불러오기 (작성자 제외)
            let contributors = [];
            let page = 1;
            while (true) {
              const { data } = await github.rest.repos.listContributors({
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 100,
                page
              });
              if (data.length === 0) break;
              contributors = contributors.concat(data.map(u => u.login));
              page++;
            }
            // PR 작성자 제외
            const author = context.payload.pull_request.user.login;
            contributors = contributors.filter(u => u !== author);

            // 랜덤 2명(2명 미만이면 남은 만큼)
            const reviewers = contributors.sort(() => 0.5 - Math.random()).slice(0, 2);

            // 리뷰어 할당
            if (reviewers.length > 0) {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                reviewers: reviewers
              });
            }

            // PR 본문에 리뷰어 기록 (후속 step에서 활용)
            const body = context.payload.pull_request.body || "";
            const reviewersNote = `<!-- reviewers: ${reviewers.join(',')} -->`;
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: `${body}\n${reviewersNote}`
            });

            console.log("Review candidate contributors:", contributors);
            console.log("Assigned reviewers:", reviewers);

      # 2️⃣ 리뷰 제출 시: 리뷰어 모두 승인 확인 & 자동 머지
      - name: Auto merge if reviewers all approved (or none assigned)
        if: github.event_name == 'pull_request_review'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_ACCESS_TOKEN }}
          script: |
            const pr_number = context.payload.pull_request.number;

            // PR 본문에서 리뷰어 정보 추출
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            });
            const body = pr.body || "";
            const reviewersMatch = body.match(/<!-- reviewers: ([^>]*)-->/);
            const reviewers = reviewersMatch && reviewersMatch[1].trim()
              ? reviewersMatch[1].split(',').map(r => r.trim()).filter(r => r)
              : [];

            // 리뷰어가 한 명도 없으면 바로 머지
            if (reviewers.length === 0) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr_number
              });
              console.log("No reviewers assigned. PR auto merged.");
              return;
            }

            // 각 리뷰어의 마지막 리뷰 상태 확인
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            });

            const reviewStates = {};
            reviewers.forEach(reviewer => {
              const userReviews = reviews.filter(r => r.user.login === reviewer);
              if (userReviews.length > 0) {
                reviewStates[reviewer] = userReviews[userReviews.length - 1].state;
              }
            });

            console.log("Review states:", reviewStates);

            // CHANGES_REQUESTED가 하나라도 있으면 PR 반려(닫기)
            if (Object.values(reviewStates).includes("CHANGES_REQUESTED")) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr_number,
                body: `⚠️ PR 자동 반려: 리뷰어 중 한 명 이상이 변경 요청했습니다.`
              });
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr_number,
                state: "closed"
              });
              console.log("PR closed due to changes requested.");
              return;
            }

            // 모든 리뷰어가 APPROVED면 자동 머지
            if (reviewers.length > 0 && reviewers.every(r => reviewStates[r] === "APPROVED")) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr_number
              });
              console.log("All reviewers approved. PR auto merged.");
            } else {
              console.log("Waiting for all reviewers to approve.");
            }
